# Generated by Django 3.0.6 on 2020-05-17 20:39

import accounts.models
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('identifier', models.EmailField(max_length=50, unique=True, verbose_name='e-mail')),
                ('firstName', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('lastName', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=40, verbose_name='city')),
                ('zipCode', localflavor.us.models.USPostalCodeField(blank=True, max_length=2, verbose_name='zip code')),
                ('telephoneNumber', models.CharField(max_length=12, verbose_name='telephone number')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='avatar')),
                ('dataJoined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'userts',
            },
            managers=[
                ('object', accounts.models.ShopUserManager()),
            ],
        ),
    ]
