# Generated by Django 3.0.6 on 2020-05-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shopuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='telephoneNumber',
            field=models.CharField(blank=True, max_length=12, verbose_name='telephone number'),
        ),
    ]
