# Generated by Django 3.0.6 on 2020-05-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200517_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='dataJoined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data joined'),
        ),
    ]
