# Generated by Django 3.0.6 on 2020-05-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsMaintain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
    ]
