# Generated by Django 3.0.6 on 2020-05-18 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productsMaintain', '0002_auto_20200518_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productsOfTheCategory', to='productsMaintain.Category'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandsOfTheCategory', to='productsMaintain.Category'),
        ),
    ]
