# Generated by Django 3.0.6 on 2020-05-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsMaintain', '0003_auto_20200518_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='brandsOfTheCategory', to='productsMaintain.Category'),
        ),
    ]
