# Generated by Django 3.0.6 on 2020-05-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsMaintain', '0004_auto_20200518_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5, verbose_name='Size')),
                ('value', models.IntegerField(verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'ordering': ('value',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='ProductWithThisSize', to='productsMaintain.Size'),
        ),
    ]
