# Generated by Django 3.0.6 on 2020-05-27 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsMaintain', '0006_auto_20200519_1937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('payTime', models.DateTimeField(blank=True, verbose_name='Payment time')),
                ('paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('braintreeId', models.CharField(blank=True, max_length=200)),
                ('deliveredToAnotherAddress', models.BooleanField(default=False, verbose_name='Delive to another address')),
                ('firstNameD', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('lastNameD', models.CharField(blank=True, max_length=30, verbose_name='Last name')),
                ('addressD', models.CharField(blank=True, max_length=100, verbose_name='Address')),
                ('cityD', models.CharField(blank=True, max_length=40, verbose_name='City')),
                ('zipCodeD', localflavor.us.models.USPostalCodeField(blank=True, max_length=2, verbose_name='Zip code')),
                ('telephoneNumberD', models.CharField(blank=True, max_length=12, verbose_name='Telephone number')),
                ('extraInfoD', models.TextField(blank=True, verbose_name='Extra information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('costPerItem', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Cost per item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedItems', to='cart.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderWrappers', to='productsMaintain.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordersWithThisSize', to='productsMaintain.Size')),
            ],
        ),
    ]
